language: C++

compiler:
    - gcc
    
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - libboost-test-dev

install:
    - wget --no-check-certificate http://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz 
    - tar xf cmake-3.3.2-Linux-x86_64.tar.gz
script:
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    - cmake-3.3.2-Linux-x86_64/bin/cmake . -DCMAKE_BUILD_TYPE="Debug"
    - cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target benchmark
    - cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target testit
    - cmake-3.3.2-Linux-x86_64/bin/cmake . -DCMAKE_BUILD_TYPE="Release"
    - cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target benchmark
    - cmake-3.3.2-Linux-x86_64/bin/cmake --build . --target testit
