language: C++

compiler:
    - clang
    - gcc
    
before_script: 
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    - sudo apt-get install libboost-test-dev

script:
    - cmake .
    - cmake --build .
    - cmake --build . --target benchmark
    - cmake --build . --target testit
